name: Clone from Source

on:
  repository_dispatch:
    types: [clone-repo]

jobs:
  mirror:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      REPO_NAME: ${{ github.event.client_payload.repoName }}
      SOURCE_URL: ${{ github.event.client_payload.sourceURL }}
      OWNER: ${{ github.event.client_payload.owner }}

    steps:
      - name: Debug inputs
        run: |
          echo "Repo name: ${REPO_NAME}"
          echo "Source URL: ${SOURCE_URL}"
          echo "Owner: ${OWNER}"

      - name: Validate inputs
        run: |
          if [ -z "${REPO_NAME}" ] || [ -z "${SOURCE_URL}" ] || [ -z "${OWNER}" ]; then
            echo "❌ Missing REPO_NAME, SOURCE_URL, or OWNER"
            exit 1
          fi

      - name: Mirror from source to target
        run: |
          set -e
          workdir=$(mktemp -d)
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "Repo Cloner Action"

          cd "$workdir"
          echo "Cloning ${SOURCE_URL}..."
          git clone --bare "${SOURCE_URL}" src.git

          cd src.git
          echo "Adding target remote: https://github.com/${OWNER}/${REPO_NAME}.git"
          git remote add target "https://${GH_TOKEN}@github.com/${OWNER}/${REPO_NAME}.git"

          echo "Pushing mirror to target..."
          git push --mirror target

      - name: ✅ Done
        run: echo "Repository ${SOURCE_URL} successfully mirrored to ${OWNER}/${REPO_NAME}"
