name: Import Repository

on:
  workflow_dispatch:
    inputs:
      sourceURL:
        description: "Source repository Git URL"
        required: true
      repoName:
        description: "New repository name"
        required: true

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout empty repo
        uses: actions/checkout@v4

      - name: Create new GitHub repo
        id: create_repo
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/user/repos \
               -d "{\"name\": \"${{ github.event.inputs.repoName }}\", \"private\": false}" \
               > response.json

          echo "Repo URL: $(jq -r '.html_url' response.json)"
          echo "repo_url=$(jq -r '.html_url' response.json)" >> $GITHUB_OUTPUT

      - name: Clone source and push mirror
        run: |
          git clone --bare "${{ github.event.inputs.sourceURL }}" source-repo
          cd source-repo
          git push --mirror "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.inputs.repoName }}.git"

      - name: Done
        run: echo "✅ Imported ${{ github.event.inputs.sourceURL }} into ${{ steps.create_repo.outputs.repo_url }}"
